name: Deploy FE

on:
  push:
    branches: ["main"]
    paths:
      - "fe/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy via FTP (No TLS)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FE_FTP_HOST }}
          username: ${{ secrets.FE_FTP_USER }}
          password: ${{ secrets.FE_FTP_PASS }}
          local-dir: ./frontend
          protocol: ftp
          port: 21
          security: none
