name: Deploy Frontend (HTML)

on:
  push:
    branches: [main]
    paths: ['frontend/**'] # Chỉ chạy khi Frontend thay đổi

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Sync Frontend files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FE_FTP_HOST }}
          username: ${{ secrets.FE_FTP_USERNAME }}
          password: ${{ secrets.FE_FTP_PASSWORD }}
          local-dir: ./frontend/      # Lấy file từ thư mục frontend/
          server-dir: /www.testoss.somee.com/ # ĐƯỜNG DẪN ĐÍCH ĐÃ XÁC NHẬN
          protocol: ftp                   # Giao thức bảo mật (để tối ưu kết nối)
