name: Deploy Frontend (HTML)

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  # Kích hoạt khi chỉ folder frontend thay đổi

jobs:
  web-deploy:
    name: Deploy FE via FTP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Chỉ cần kéo code và deploy (không cần build)
      - name: Sync Frontend files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FE_FTP_HOST }}
          username: ${{ secrets.FE_FTP_USERNAME }}
          password: ${{ secrets.FE_FTP_PASSWORD }}
          local-dir: ./frontend/      # Source: Thư mục frontend
          server-dir: ./htdocs/  # Target: Thư mục gốc trên host FE
          protocol: ftp 
          security: loose